-- ============================================================
-- Buyer directory — Company list (2025) for platform.pdf
-- Idempotent inserts; does not remove legacy Plastic/Stamping seed (017)
-- ============================================================

INSERT INTO public.platform_directory_contacts (segment, company_name, country, contact_name, "position", email, phone, website, source_ref)
SELECT
  e->>'segment',
  e->>'company_name',
  coalesce(nullif(trim(e->>'country'), ''), 'Russia'),
  nullif(trim(e->>'contact_name'), ''),
  nullif(trim(e->>'position'), ''),
  nullif(lower(trim(e->>'email')), ''),
  nullif(trim(e->>'phone'), ''),
  nullif(trim(e->>'website'), ''),
  e->>'source_ref'
FROM jsonb_array_elements($company_list_2025$[
  {"segment":"Tool maker","company_name":"HYS","country":"China","contact_name":"Bill Wen","position":"Oversea Marketing Director","email":"wqx@hysmould.com","phone":null,"website":"http://www.hysmould.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"HYS","country":"France","contact_name":"Bill Wen","position":"Oversea Marketing Director","email":"wqx@hysmould.com","phone":null,"website":"http://www.hysmould.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"BM","country":"China","contact_name":"Louis Liu","position":null,"email":"louis@brothermold.com","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"BASIS","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"IEC MOLD","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"SUNWILL","country":"China","contact_name":"Percy","position":"Director","email":"sdmjsm07@sunwill.com.cn","phone":"+86-13923270928","website":"www.sunwill.com.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"AD MOLD","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"SJ GROUP","country":"China","contact_name":"Jimmy","position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"CK MOLD","country":"China","contact_name":"Candy","position":"Sales","email":"candy@ck-mould.com","phone":null,"website":"http://www.ck-mould.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"SAIHAO","country":"China","contact_name":"Johnny Zhu","position":"Marketing","email":"yu.zhu@saihao.com.cn","phone":"+86-18857668294","website":"http://www.saihao.com/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"AWT","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"COSCO","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"ANGO MOLD","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"FORM SERVICE","country":"Russia","contact_name":"Denis Merkulov","position":"Project Manager","email":"denis.merkulov@formservice.eu","phone":"+7 (903) 331 43 84","website":"www.formservice.eu","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"FORSH","country":"Russia","contact_name":"Sergey Sidyakin","position":null,"email":"sidyakinsa@forsh.ru","phone":null,"website":"www.forsh.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"FORSH","country":"Russia","contact_name":"Dmitry Bubnov","position":"Marketing Director","email":"d.bobnev@forsh.ru","phone":null,"website":"www.forsh.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"AVIACAM","country":"Russia","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"Togliatti Detal Service","country":"Russia","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Engraving","company_name":"STANDEX MOLD TECH","country":"Russia","contact_name":"Artem Sbitnev","position":"General Manager","email":"sbitnev@mold-tech.com","phone":"+7-906-358-9948","website":"www.standexrus.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CF maker","company_name":"BOREY","country":"China","contact_name":"Melinda","position":null,"email":"melinda@boruidg.com","phone":null,"website":"www.dgboray.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CF maker","company_name":"MS","country":"China","contact_name":"Tayk","position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CF maker","company_name":"TELMA","country":"Italy","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CF maker","company_name":"KT MISSION","country":"China","contact_name":null,"position":null,"email":"joeli@missiongauge.com","phone":"+86-18819110041","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CF maker","company_name":"ZHCF","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Carmaker","company_name":"NAMI","country":"Russia","contact_name":"Konstantin Medvedsky","position":"Director","email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Carmaker","company_name":"AVTOVAZ","country":"Russia","contact_name":"Roman Borovsky","position":"Project Manager","email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Carmaker","company_name":"RENAULT","country":"Russia","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Carmaker","company_name":"PCMA","country":"Russia","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Engineering","company_name":"SEGULA TECHNOLOGY","country":"France","contact_name":"Franck Ghrenassia","position":"CEO","email":"franck.ghrenassia@segula.fr","phone":null,"website":"www.segula.fr","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Engineering","company_name":"SEGULA TECHNOLOGY","country":"Russia","contact_name":"Alexander","position":"General Manager","email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Engineering","company_name":"EXPLEO","country":"Russia","contact_name":"Anatoly Shinakov","position":"General Manager","email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Engineering","company_name":"STRF TECHNOLOGY","country":"Russia","contact_name":"Anna Dunaeva","position":"General Manager","email":"anna.dunaeva@strfgroup.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Prototype","company_name":"3D INITIAL","country":"China","contact_name":"Steven Mereuta","position":"General Manager","email":"plotthouse@hotmail.com","phone":"+8618262686700","website":"www.initial3d.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Logistic","company_name":"SAMARA TRANSPORT","country":"Russia","contact_name":"Andrey Bondarenko","position":"Manager","email":"stuandrey5@gmail.com","phone":"+7(939)718-11-63","website":"http://samtransupr.ru/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"NINGBO XINGLI AUTO MOULD CO., LTD","country":"China","contact_name":"RongWu Wu","position":"General Manager","email":"Rongwu.wu@xlmould.cn","phone":"8613805859551","website":"www.xlmould.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"3D Printing","company_name":"VALTEO LIMITED","country":"China","contact_name":"Steven Mereuta","position":"CEO","email":null,"phone":"+373 79 576 442","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"CES Co","country":"Korea","contact_name":"Young-Ju, Beak","position":"Director","email":"yjbaek@cescom.co.kr","phone":"82-10-9153-6777","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"Xingli Mould","country":"China","contact_name":"Tao Wen","position":"Sales Manager","email":"tao.wen@xlmould.cn","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"DAAZ / ДААЗ","country":"Russia","contact_name":"Albert Gabaidulin","position":"Technical Director","email":"albert.gabaidulin@oat-group.ru","phone":"8 965-695-4-84","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"DAAZ / ДААЗ","country":"Russia","contact_name":"Плаксин Михаил Александрович","position":null,"email":"mikhail.plaksin@oat-group.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"DAAZ / ДААЗ","country":"Russia","contact_name":"Natalia Banketova","position":"Инженер по подготовке производства","email":"natalia.banketova@oat-group.ru","phone":"7 (84235) 5-20-73","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Гестамп","country":"Russia","contact_name":"Evgeniya V. Nakhutsrishvili","position":null,"email":"enakhutsrishvili@ru.gestamp.com","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Магна Петерформ","country":"Russia","contact_name":"Starostin, Vladimir","position":null,"email":"vladimir.starostin@magna.com","phone":null,"website":"http://www.hysmould.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Джошкуноз","country":"Russia","contact_name":"Эджевит ОКТЕМ","position":"гендир","email":"eoktem@coskunoz.ru","phone":"7 937 003 92 72","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Джошкуноз","country":"Russia","contact_name":"Askin OZCICEK","position":"Russia project manager","email":"aozcicek@coskunoz.com","phone":"90 224 324 54 08","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Джошкуноз","country":"Russia","contact_name":"Марсель Прокофьев","position":"Директор по продажам","email":"mprokofyev@coskunoz.ru","phone":"7 937 585 01 48","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Джошкуноз","country":"Russia","contact_name":"Ильдар Мамлеев","position":"Начальник отдела продаж","email":"imamleev@coskunoz.ru","phone":"7 937 004 66 96","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Джошкуноз","country":"Russia","contact_name":"Петр Шишкин","position":"директор по качеству","email":"pshishkin@coskunoz.ru","phone":"7 937 281 17 18","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Джошкуноз","country":"Russia","contact_name":"Сабина Картал","position":"специалист по продажам","email":"skartal@coskunoz.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Джошкуноз","country":"Russia","contact_name":"Юрий Лобанов","position":"руководитель проекта","email":"ylobanov@coskunoz.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Джошкуноз","country":"Russia","contact_name":"Фатих Коджакайа","position":"коммерческий директор","email":"fkocakaya@mmk-coskunoz.ru","phone":"7 927 455 01 70","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ББС","country":"Russia","contact_name":"Виктория Нестерова","position":null,"email":"victoria.nesterova@b2b-s.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ТМЗ","country":"Russia","contact_name":"Давыдов Александр","position":"гендир","email":"office@tmz-tlt.ru","phone":"+7 902 373 64 31","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"«ЭНЕРГОТЕХМАШ» ГК «Акрон Холдинг»","country":"Russia","contact_name":"Новоженин Александр Владимирович","position":"Руководитель группы по продажам автокомпонентов","email":"novozhenin_av@akron-holding.ru","phone":"89178213472","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ТЗТО","country":"Russia","contact_name":"Anna ILYINA / Анна Ильина","position":"Key Account Manager","email":"A.Ilina@groupdsk.ru","phone":"7 927 213 4043","website":"www.groupdsk.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ТЗТО","country":"Russia","contact_name":"Станислав Федортов","position":"Директор по продажам и маркетингу","email":"s.fedotov@groupdsk.ru","phone":"7 929 710 28 42","website":"www.groupdsk.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ООО РОБОЛА","country":"Russia","contact_name":"Рожков Роман Юрьевич","position":"Ген дир","email":"r.rozhkov@robola.ru","phone":"7 927 774 78 31","website":"www.robola.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ООО РОБОЛА","country":"Russia","contact_name":"Царев Алексей Иванович","position":"Зам ген дира по развитию","email":"tsarev@robola.ru","phone":"7 927 787 41 67","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ООО РОБОЛА","country":"Russia","contact_name":"Андрей Нагорнов / Andrei Nagornov","position":"Зам. ген. дира по коммерции","email":"a.nagornov@robola.ru","phone":"79631186771","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ЛМЗ-Прогресс","country":"Russia","contact_name":"Кириченко Роман Вячеславович","position":null,"email":"info@redroller.ru","phone":"89372170471","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ЛМЗ-Прогресс","country":"Russia","contact_name":"Очкасов Андрей Георгиевич","position":null,"email":"info@redroller.ru","phone":"89027402733","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ПОЛАД","country":"Russia","contact_name":"Светлов Евгений Александрович","position":"Директор по развитию","email":"kurganskyvy@polad.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ПОЛАД","country":"Russia","contact_name":"Путин Иван / Ivan Putin","position":"Руководитель проектов","email":"putinia@polad.ru","phone":"7 (8482) 701-501, +7-961-390-09-46","website":"www.polad.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ПОЛАД","country":"Russia","contact_name":"Пахомов Алексей Юрьевич","position":"Зам. директора по проектам","email":"pahomovau@polad.ru","phone":"7 (8482) 701-501 ext. 14-91, 7 929 716 43 41","website":"www.polad.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ПОЛАД","country":"Russia","contact_name":"Вольф Владислав Борисович","position":"Руководитель проектов","email":"volfvb@polad.ru","phone":"78482701501, 79278992571","website":"www.polad.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ПОЛАД","country":"Russia","contact_name":"Чуваков Николай","position":"Руководитель проекта","email":"chuvakovni@polad.ru","phone":"78482701501, 79626140128","website":"www.polad.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"МИКРОТЕХ","country":"Russia","contact_name":"Громотков Дмитрий Вячеславович","position":"Директор","email":"Dg@microtech.ru","phone":"7 903 013 04 20","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"МИКРОТЕХ","country":"Russia","contact_name":"Терешко Игорь Александрович","position":"Директор по качеству","email":"igor.tereshko@microtech.ru","phone":"7 906 641 0435","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Альфа Автоматив Технолоджиз / ААТ","country":"Russia","contact_name":"Неклюдов Сергей Владимирович","position":"Менеджер по продажам и развитию бизнеса","email":"s.nekludov@aat.moscow","phone":"7-495-783-17-45 доб. 176, 7-962-983-89-85","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"Лада-пласт-Т","country":"Russia","contact_name":"Филько Юрий Евгеньевич","position":"Исполнительный директор","email":"yf@ladaplast.ru","phone":"7-927-268-16-41","website":"www.ladaplast.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Stamping","company_name":"ВМ Автомотив","country":"Russia","contact_name":"Dizhenin Vasiliy","position":"Генеральный директор","email":"v.dizhenin@wmautomotive.ru","phone":"7 9270254364","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"ТКА","country":"Russia","contact_name":"Александр Процанов","position":null,"email":"peotka@tlt.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Сатурно","country":"Russia","contact_name":"Елена Богданова","position":null,"email":"e.bogdanova@saturno-tp.com","phone":"7 (9171) 28-36-18","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"АE2","country":"Russia","contact_name":"Сергей Медведев","position":null,"email":"s.medvedev@ae-2.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"APEX","country":"Russia","contact_name":"Илья Елисеев","position":null,"email":"i.eliseev@apextlt.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"СЭД (LLC Krista / ООО Криста)","country":"Russia","contact_name":"Марина Москаева","position":"Специалист по продажам","email":"mmoskaeva@krista63.ru","phone":"+7 8464 37 04 92, +7 937 663 25 00","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"СЭД (LLC Krista / ООО Криста)","country":"Russia","contact_name":"Василий Малов","position":"зам.тех.дир","email":"malov.vy@krista63.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"СЭД (LLC Krista / ООО Криста)","country":"Russia","contact_name":"Валерий Марченко","position":"Тех. Директор","email":"marchenko.va@kristagroup.com","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"СЭД (LLC Krista / ООО Криста)","country":"Russia","contact_name":"Мартынов Н.Н.","position":"Коммерческий директор","email":"nmartynov@kristagroup.com","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Восток-Амфибия","country":"Russia","contact_name":"Усанов Геннадий Викторович","position":"Коммерческий директор","email":"usanov@amfiby.ru","phone":"+79674605900, 8(84342)5-69-09","website":"http://www.amfib.ru/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Ладапласт-Т","country":"Russia","contact_name":"Шипило Павел Михайлович","position":"Дир. по развитию","email":"ShipiloP@mail.ru","phone":"7 927 771-31-22, +7 8482 63-59-05","website":"www.ladaplast.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Ладапласт-Т","country":"Russia","contact_name":"Филько Юрий Евгеньевич","position":"Исполнительный директор","email":"yf@ladaplast.ru","phone":"7-927-268-16-41","website":"www.ladaplast.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Megaplast, Тольятти","country":"Russia","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Avangard, Тольятти","country":"Russia","contact_name":null,"position":null,"email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Идеал Пласт","country":"Russia","contact_name":"Башкин Юрий Анатольевич","position":"Исполнительный директор","email":"ideal-vl@mail.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"ООО «АВТОКОМПЛЕКТ»","country":"Russia","contact_name":"Алена Лабынцева","position":"Заместитель директора по экономике","email":"labyntseva.an@avtocomplekt-tlt.ru","phone":"79272137661","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"ГК «СТАНДАРТПЛАСТ»","country":"Russia","contact_name":"Василий Морев","position":"Руководитель направления Промышленные предприятия","email":"v_morev@stplus.ru","phone":"7-999-730-10-32","website":"www.stp-world.com / www.stp-russia.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Автокомпонент","country":"Russia","contact_name":"Безручкин Антон Иванович","position":"Директора по проектам","email":"a.bezruchkin@autocomponent.info","phone":null,"website":"www.autocomponent.info","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Автокомпонент","country":"Russia","contact_name":"Катков Михаил Сергеевич","position":"Начальник коммерческой службы","email":"m.katkov@autocomponent.info","phone":"7 (930) 717-42-62","website":"www.autocomponent.info","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Автокомпонент","country":"Russia","contact_name":"Захаров Илья","position":"инженер-конструктор","email":"l.setdikova@autocomponent.info","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Автокомпонент","country":"Russia","contact_name":"Лычагова Юлия Николаевна","position":null,"email":"yu.lychagova@autocomponent.info","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Автокомпонент","country":"Russia","contact_name":"Мельников Андрей","position":null,"email":"a.melnikov@autocomponent.info","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"КинельАгропласт","country":"Russia","contact_name":"Дмитрий Вячеславович Муратов","position":"зам. генерального директора","email":"dmuratov@mail.kiap.ru","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"МС Автомотив","country":"Russia","contact_name":"Vadim Islamov","position":"Project management","email":"vadim.islamov@msa.group","phone":"7 962 518 36 09","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Альта Северо-Запад","country":"Russia","contact_name":"Николай Станиславов","position":"Технический директор","email":"n.stanislavov@alta-car.ru","phone":"+7 (812) 539 54 65, +7 (967) 342 24 94","website":"https://alta-car.ru/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Paint & Coating","company_name":"Collini","country":"Russia","contact_name":"Давид Гарафутдинов","position":"Руководитель маркетинга и сбыта","email":"dgarafutdinov@collini.eu","phone":"79150224739","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Paint & Coating","company_name":"ООО «БЕЛЛЕЗА ГРУПП»","country":"Russia","contact_name":"Емельянов Андрей","position":"Исполнительный директор","email":"emelyanov@bellezagroup.ru","phone":"79171338404","website":"www.bellezagroup.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Paint & Coating","company_name":"ООО «БЕЛЛЕЗА ГРУПП»","country":"Russia","contact_name":"Волков Кирилл Алексеевич","position":"Директор по развитию","email":"k.volkov@bellezagroup.ru","phone":"8-987-935-09-03","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Materials","company_name":"Rusavtoplast","country":"Russia","contact_name":"Оборудование — Юрий; сырьё — Роман и Татьяна","position":null,"email":"officetolyatti@tathimplast.ru","phone":"+7 (8482) 698-200","website":"https://rusavtoplast.ru/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Avtoritet Plast Plus","country":"Russia","contact_name":null,"position":null,"email":"avpplast@yandex.ru","phone":"+79376600163, +7 (937) 232-30-05","website":"avtoritetplast.ru","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Materials","company_name":"ТЗЖБИ","country":"Russia","contact_name":"Отдел снабжения / технический / производственный / приемная","position":null,"email":"snab@tzzbi.ru","phone":"+7 (8482) 558-492","website":"https://tzzbi.ru/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Plastic","company_name":"Autolive","country":"Russia","contact_name":null,"position":null,"email":"sales@avtoliv.ru","phone":"+7 848 242 35 70","website":"https://avtoliv.ru/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Materials","company_name":"Mir metalla","country":"Russia","contact_name":null,"position":null,"email":"mail@mirmetalla.com","phone":"+7 (8482) 77-33-11","website":"https://www.mirmetalla.com/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Materials","company_name":"Doka","country":"Russia","contact_name":null,"position":null,"email":null,"phone":"8 (8482) 40-41-01","website":"https://doka-steel.ru/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Automation","company_name":"TDS-63","country":"Russia","contact_name":null,"position":null,"email":"tds-63@yandex.ru","phone":"+7 927 775 66 66","website":"https://www.tds-63.ru/","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"cabels","company_name":"Farial","country":"Russia","contact_name":null,"position":null,"email":"sales@farial.ru","phone":"+7 (846) 269-50-50","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CF maker","company_name":"MinSheng","country":"China","contact_name":"Sue Chen","position":null,"email":"sue@minsheng-cf.com","phone":"+8618018796050","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CF maker","company_name":"HISUN","country":"China","contact_name":"Tracy","position":null,"email":"tracy.li@hisun-auto.com","phone":"0086-15876978940","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CF maker","company_name":"TTM","country":"China","contact_name":"Richard Zhang","position":"Sales Manager","email":"sales1@ttmgauge.com","phone":"0086-13129568028","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Die Casting","company_name":"TTM","country":"China","contact_name":"Richard Zhang","position":"Sales Manager","email":"sales1@ttmgauge.com","phone":"0086-13129568028","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"TTM","country":"China","contact_name":"Richard Zhang","position":"Sales Manager","email":"sales1@ttmgauge.com","phone":"0086-13129568028","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Automation","company_name":"TTM","country":"China","contact_name":"Richard Zhang","position":"Sales Manager","email":"sales1@ttmgauge.com","phone":"0086-13129568028","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Die Casting","company_name":"GLYZ","country":"China","contact_name":"Steven Yuan","position":null,"email":"steven@sz6y.com","phone":"13924602185","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Solar Enerhy","company_name":"Rising Power","country":"China","contact_name":"Cyndi / Steven","position":"Director","email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Solar Enerhy","company_name":"Sushui","country":"China","contact_name":"Steven / Shon","position":"Director","email":null,"phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Solar Enerhy","company_name":"Yunqida","country":"China","contact_name":null,"position":null,"email":"business@yunqida-ne.com","phone":"86-13808874548","website":"www.yunqida-ne.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Solar Enerhy","company_name":"ZB Power","country":"China","contact_name":"Tony Zhang","position":"Manager","email":"272622374@qq.com","phone":"15986839659","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Solar Enerhy","company_name":"ZB Power","country":"China","contact_name":"Mr. Li","position":"Manager","email":"272622374@qq.com","phone":"13823202983","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Laser cutting","company_name":"Jinan Vmade CNC machines Co.","country":"China","contact_name":"Sales","position":"Sales Manager","email":"Sales@vmadecnc.com","phone":"18615631535","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"IMM machines","company_name":"Haituo","country":"China","contact_name":"Brian","position":"General Manager","email":"info@china-haituo.com","phone":"13566518412","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"MES Visualization","company_name":"Ruiduoyi","country":"China","contact_name":"Sales","position":"Sales Manager","email":"Sales@ruiduoyi.com","phone":"0755-29360785","website":"www.ruiduoyi.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Milling Tools","company_name":"Dong Lian","country":"China","contact_name":"Sales","position":"Sales Manager","email":"Sales@donglian-tools.com","phone":"15013178030","website":"www.donglian-tools.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"Aceray","country":"China","contact_name":"Daniel","position":"Sales Manager","email":"daniel@aceraytech.com","phone":"15766162983","website":"www.aceraytech.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Rubber Machines","company_name":"Zhejiang Yuyao Huacheng","country":"China","contact_name":"Sales","position":"Sales Manager","email":"hc@hc-machine.com","phone":"0574-62501510","website":"www.hc-machine.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"GOM","country":"China","contact_name":"Laurence Wu","position":"Sales Manager","email":"Laurence.wu@go-mould.com","phone":"13790360546","website":"www.go-mould.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"Kunshan Wushuang Metal Tech","country":"China","contact_name":"Sales","position":"Sales Manager","email":"Sales@t2mold.com","phone":"13382151579","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"Kyledy Mould","country":"China","contact_name":"Roger Cao","position":"Sales Manager","email":"roger@kyledy-mould.com","phone":"13267022691","website":"www.kyledy-mould.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"New Century Tooling","country":"China","contact_name":"Nina Luo","position":"Sales Manager","email":"ninaluo@newcenturytooling.com","phone":"+8613189511906","website":"www.newcenturytooling.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"AMSL Tooling","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":"www.amsl-tooling.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"TopNC","country":"China","contact_name":null,"position":null,"email":null,"phone":"4008205993","website":"www.topnc.com.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"Neway","country":"China","contact_name":"info","position":"Sales","email":"cncsale@neway.com.cn","phone":"51266071116","website":"www.newaycnc.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"Jisen","country":"China","contact_name":null,"position":null,"email":null,"phone":"57687222206","website":"www.zjjszn.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"JOY","country":"China","contact_name":null,"position":null,"email":"13792706610@163.com","phone":null,"website":"www.sdzhuoyicnc.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"Xinzhe","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":"www.nj-xzsk.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"SMK","country":"China","contact_name":null,"position":null,"email":"Senmarkcnc@163.com","phone":"18260266610","website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"3Q","country":"China","contact_name":null,"position":null,"email":null,"phone":"4006402005","website":"www.sk2005.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Turning","company_name":"Tsugami","country":"China","contact_name":null,"position":null,"email":null,"phone":"13511317818","website":"www.tsugami.com.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Turning","company_name":"Primacon","country":"China","contact_name":null,"position":null,"email":"primacon@163.com","phone":"17326081599","website":"www.primacon.com.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Turning","company_name":"Redsine","country":"China","contact_name":"Tang","position":null,"email":"tang@redsine.com.cn","phone":null,"website":null,"source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Turning","company_name":"Citizen","country":"China","contact_name":null,"position":null,"email":"szjx@shanze-china.com","phone":"0512-3688099","website":"www.shanze-china.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"ARMS","country":"China","contact_name":"Tao Wei","position":null,"email":"jdskbsd@163.com","phone":"0567-87283970","website":"www.jdcnc.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"NAIGOO","country":"China","contact_name":"Andy Ye","position":"Manager","email":"naigoogd@163.com","phone":"13829224575","website":"www.naigoo.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"CNC","company_name":"Kachi","country":"China","contact_name":null,"position":null,"email":null,"phone":"13967627615","website":"www.kaiji.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"EDM","company_name":"Amasun","country":"China","contact_name":null,"position":null,"email":"tzyake@tzkake.com","phone":"18015512255","website":"www.amsedm.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"EDM","company_name":"DMNC & OVSO","country":"China","contact_name":null,"position":null,"email":null,"phone":null,"website":"www.dmcn-edm.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"EDM","company_name":"Kingred","country":"China","contact_name":null,"position":null,"email":null,"phone":"400-0990619","website":"www.kingred-sz.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"JKM","country":"China","contact_name":null,"position":null,"email":"2641653003@qq.com","phone":"13335879432","website":"www.wzjfmj.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"Cowwin","country":"China","contact_name":"Alex Liang","position":"Business Technical Director","email":"alex.liang@cowwin.com","phone":"+8618825531236","website":"www.cowwin.com.cn","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Tool maker","company_name":"SHENZHEN TEC-SHINE TECHNOLOGY CO","country":"China","contact_name":"Donna Deng","position":"Business Development Manager","email":"donna@tec-shine.com","phone":"+86(0)13410473760","website":"www.tec-shine.com","source_ref":"Company list (2025) for platform.pdf"},
  {"segment":"Steel material","company_name":"Crucible","country":"China","contact_name":"Sales","position":"Sales","email":"sales@crucible.com","phone":"1-800-365-1180","website":"https://www.crucible.com/Index.aspx","source_ref":"Company list (2025) for platform.pdf"}
]$company_list_2025$::jsonb) AS t(e)
WHERE NOT EXISTS (
  SELECT 1 FROM public.platform_directory_contacts p
  WHERE lower(trim(p.company_name)) = lower(trim(e->>'company_name'))
    AND coalesce(lower(trim(p.email)), '') = coalesce(lower(trim(e->>'email')), '')
    AND coalesce(lower(trim(p.contact_name)), '') = coalesce(lower(trim(e->>'contact_name')), '')
    AND p.segment = (e->>'segment')
);

COMMENT ON TABLE public.platform_directory_contacts IS
  'Imported B2B contacts (buyer directory); includes Company list (2025) for platform.pdf + legacy Plastic/Stamping PDFs. Superadmin only.';

-- Mirror 2025 list into supplier directory (same rows; idempotent if 020 already mirrored older contacts)
INSERT INTO public.platform_registered_suppliers (
  segment,
  company_name,
  industry,
  country,
  contact_name,
  "position",
  email,
  phone,
  website,
  source_ref,
  metadata
)
SELECT
  p.segment,
  p.company_name,
  NULL,
  p.country,
  p.contact_name,
  p."position",
  p.email,
  p.phone,
  p.website,
  p.source_ref || ' · supplier directory mirror',
  coalesce(p.metadata, '{}'::jsonb) || jsonb_build_object('buyer_directory_row', p.id::text)
FROM public.platform_directory_contacts p
WHERE p.source_ref = 'Company list (2025) for platform.pdf'
  AND NOT EXISTS (
    SELECT 1
    FROM public.platform_registered_suppliers r
    WHERE lower(trim(r.company_name)) = lower(trim(p.company_name))
      AND coalesce(lower(trim(r.email)), '') = coalesce(lower(trim(p.email)), '')
      AND coalesce(lower(trim(r.contact_name)), '') = coalesce(lower(trim(p.contact_name)), '')
      AND coalesce(r.segment, '') = p.segment
  );

NOTIFY pgrst, 'reload schema';
